"""initial schema

Revision ID: 213cc1f8aef6
Revises: 
Create Date: 2015-08-14 12:16:30.219671

"""

# revision identifiers, used by Alembic.
revision = '213cc1f8aef6'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user', sa.Unicode(length=64), nullable=True),
    sa.Column('host', sa.Unicode(length=64), nullable=True),
    sa.Column('backups', sa.Integer(), nullable=True),
    sa.Column('duplicates', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('elapsed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geocode_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user', sa.Unicode(length=64), nullable=True),
    sa.Column('host', sa.Unicode(length=64), nullable=True),
    sa.Column('requests', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('elapsed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.Unicode(length=44), nullable=False),
    sa.Column('date_taken', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', sa.Unicode(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mimetype', sa.Unicode(length=64), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature')
    )
    op.create_table('storages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stype', sa.Enum('ORIGINAL', 'BACKUP', 'CLOUD', 'DROBO', name='STORAGE_TYPE'), nullable=True),
    sa.Column('hostname', sa.Unicode(length=255), nullable=True),
    sa.Column('filepath', sa.Unicode(length=512), nullable=False),
    sa.Column('memo', sa.Unicode(length=255), nullable=True),
    sa.Column('picture_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['picture_id'], ['pictures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storages')
    op.drop_table('pictures')
    op.drop_table('geocode_log')
    op.drop_table('backup_log')
    ### end Alembic commands ###
