"""timestamps

Revision ID: 2dc6800735bf
Revises: 57c4e0c5f927
Create Date: 2015-08-12 16:36:46.793013

"""

# revision identifiers, used by Alembic.
revision = '2dc6800735bf'
down_revision = '57c4e0c5f927'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('storages', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('storages', sa.Column('modified', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storages', 'modified')
    op.drop_column('storages', 'created')
    op.drop_column('pictures', 'created')
    ### end Alembic commands ###
