"""geocoding

Revision ID: 381edcdc3cbe
Revises: 3b1a4996858b
Create Date: 2015-08-12 08:35:00.413447

"""

# revision identifiers, used by Alembic.
revision = '381edcdc3cbe'
down_revision = '3b1a4996858b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user', sa.Unicode(length=64), nullable=True),
    sa.Column('host', sa.Unicode(length=64), nullable=True),
    sa.Column('requests', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('elapsed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'pictures', sa.Column('location', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'pictures', 'location')
    op.drop_table('geocode_log')
    ### end Alembic commands ###
