"""filesize

Revision ID: 3b1a4996858b
Revises: 3c771fd8fcef
Create Date: 2015-08-09 20:40:36.262620

"""

# revision identifiers, used by Alembic.
revision = '3b1a4996858b'
down_revision = '3c771fd8fcef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('bytes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pictures', 'bytes')
    ### end Alembic commands ###
