"""backup log

Revision ID: d2dcc56d610
Revises: 2dc6800735bf
Create Date: 2015-08-12 16:59:02.690303

"""

# revision identifiers, used by Alembic.
revision = 'd2dcc56d610'
down_revision = '2dc6800735bf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user', sa.Unicode(length=64), nullable=True),
    sa.Column('host', sa.Unicode(length=64), nullable=True),
    sa.Column('backups', sa.Integer(), nullable=True),
    sa.Column('duplicates', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('elapsed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_log')
    ### end Alembic commands ###
